# 1. Pandas 核心数据类型

## 1.1 什么是Pandas

- Pandas是Python语言的一个扩展程序库，用于数据分析。
- Pandas是一个开放源码、BSD许可的库，提供高性能、易于使用的数据结构和数据分析工具。
- Pandas名字衍生自术语"panel data"（面板数据）和"Python data analysis"（Python数据分析）。
- Pandas一个强大的分析结构化数据的工具集，基础是Numpy（提供高性能的矩阵运算）。
- Pandas可以从各种文件格式比如CSV、JSON、SQL、Microsoft Excel导入数据。
- Pandas可以对各种数据进行运算操作，比如归并、再成形、选择，还有数据清洗和数据加工特征。

Pandas的主要数据结构是Series（一维数据）与DataFrame（二维数据），这两种数据结构足以处理金融、统计、社会科学、工程等领域里的大多数典型用例

## 1.2 Series

Series是一种类似于字典(dict-like)的一维数组(array-like)的对象，由下面两个部分组成:

- values:-组数据(ndarray类型)

- index:相关的数据索引标签

In [245]:
import numpy as np

import pandas as pd

from pandas import Series, DataFrame

### 1.2.1 构造Series

1. From ndarray 使用ndarray构造 是一个引用对象

In [246]:
arr1 = np.random.randint(0, 10, size=5)
arr1

array([6, 2, 6, 0, 2], dtype=int32)

In [247]:
arr1[0] = 100

In [248]:
s1 = pd.Series(data=arr1)

In [249]:
# 注意：此处是修改了arr1[0]=100之后的输出
s1

0    100
1      2
2      6
3      0
4      2
dtype: int32

In [250]:
# index用来执行Series对象的显示索引，如果没有显示设置索引，则默认使用隐示（数组索引）索引填充
s2 = pd.Series(data=arr1, index=['a', 'b', 'c', 'd', 'e'])
s2

a    100
b      2
c      6
d      0
e      2
dtype: int32

2. From List 使用列表构造 是一个副本对象

In [251]:
list('ABCD')

['A', 'B', 'C', 'D']

In [252]:
l1 = [1,2,3,4]
s3 = pd.Series(data=l1, index=list('ABCD'))
s3

A    1
B    2
C    3
D    4
dtype: int64

In [253]:
l1[0] = 100

In [254]:
l1

[100, 2, 3, 4]

In [255]:
s3

A    1
B    2
C    3
D    4
dtype: int64

3. From dict 使用字典构造

In [256]:
user_info = {
    'name': 'aaa',
    'age': 20,
    'address': 'A'
}

user_info

{'name': 'aaa', 'age': 20, 'address': 'A'}

In [257]:
# 字典构造的Series，默认使用字典的key作为Series的显示索引，values作为Series的值
pd.Series(data=user_info)

name       aaa
age         20
address      A
dtype: object

In [258]:
# NaN not a number 空数值
pd.Series(data=user_info, index=['A', 'B', 'C'])

A    NaN
B    NaN
C    NaN
dtype: object

In [259]:
pd.Series(data=user_info, index=['name', 'address', 'A'])

name       aaa
address      A
A          NaN
dtype: object

4. From scalar value
- 使用一个标量(常量或变量)构造时，必须指定index，标量会被重复匹配到每一个index

In [260]:
index = list('ABCDE')
index

['A', 'B', 'C', 'D', 'E']

In [261]:
data = [6,6,6,6,6]
pd.Series(data=data, index=index)

A    6
B    6
C    6
D    6
E    6
dtype: int64

In [262]:
pd.Series(data=6, index=index)

A    6
B    6
C    6
D    6
E    6
dtype: int64

### 1.2.2 Series属性

- name 返回Series对象的名字

- shape 返回Series对象的形状

- size 返回Series对象的元素个数

- index返回Series对象的显示案引

- values 返回Sereis对象的所有元素值

In [263]:
s = pd.Series(data=[1,2,3], index=list('ABC'), name='111')

In [264]:
s.shape

(3,)

In [265]:
s.index

Index(['A', 'B', 'C'], dtype='object')

In [266]:
s.values

array([1, 2, 3])

In [267]:
# size是元素的个数
s.size

3

In [268]:
s.name

'111'

### 1.2.3 Sereis的数学运算

Series对大多数NumPy的函数都是兼容的

1. 与非pandas对象运算

服从广播机制原则

In [269]:
s + 1

A    2
B    3
C    4
Name: 111, dtype: int64

In [270]:
# arr1 = np.array([1,2,3,4])
# arr1 + s

2. NumPy functions

In [271]:
np.power(np.array([1,2,3]), 2)

array([1, 4, 9])

In [272]:
np.power(s,2)

A    1
B    4
C    9
Name: 111, dtype: int64

3. Series之间运算
- 索引对齐原则
- 对不齐补空值，使用addksubimundiv函数处理空值

In [273]:
s

A    1
B    2
C    3
Name: 111, dtype: int64

In [274]:
s1 = pd.Series(data=np.array([2,3,4]), index=['C', 'A', 'B'])
s1

C    2
A    3
B    4
dtype: int64

In [275]:
s + s1

A    4
B    6
C    5
dtype: int64

In [276]:
s2 = pd.Series(data=[2,3,4], index=['A', 'C', 'D'])

In [277]:
s2

A    2
C    3
D    4
dtype: int64

In [278]:
s1 + s2

A    5.0
B    NaN
C    5.0
D    NaN
dtype: float64

## 1.3 DataFrame

DataFrame是一个二维的表格型数据结构，可以看做是由Series组成的字典(共用同一个索引)。

DataFrame由按一定顺序排列的【多列】数据组成，每一列的数类型可能不同。

设计初衷是将Series的使用场最从一维拓展到多维，DataFrame既有行索引，也有列索引。

- 行索引:index
- 列索引:columns
- 值:values(numpy的二维数组)

In [279]:
list1 = [1, 2, 'name']

s1 = pd.Series(data=list1)

In [280]:
# Series和ndarray一样，会强制类型统一
s1

0       1
1       2
2    name
dtype: object

In [281]:
s1.dtype

dtype('O')


### 1.3.1 构造DataFrame

In [282]:
# data-None 用于构造DataFrame的数据
# index=None, columms=None, 行列索引
# dtype=None，数据类型
# copy=False

data = np.random.randint(0, 100, size=(3, 4))
index = ['tom', 'lucy', 'alex']
columns = ['语文', '数学', '英语', '物理']
pd.DataFrame(data=data, index=index, columns=columns)

      语文  数学  英语  物理
tom   44   3  87   9
lucy  21  91  24   0
alex  21  55  23  13

1. From dict of Series or dicts 使用一个由Series构造的字典或一个字典构造

In [283]:
names=pd.Series(data=['lucy','mery','tom'], index=list('ABC'))
scores=pd.Series(data=np.random.randint(0,100, size=3), index=list('ABC'))

pd.DataFrame(data={
'names':names,
'scores':scores
})

  names  scores
A  lucy      42
B  mery       7
C   tom      21

2. From dict ofndarrays/lists 使用一个由列表或ndarray构造的字典构造

ndarrays必须长度保持一致

In [284]:
dic = {
    'name': 'lucy',
    'score': 90
}
pd.DataFrame(data=dic, index=[0])

   name  score
0  lucy     90

3. From alist of dicts 使用一个由字典构成的列表构造

In [285]:
dic1 = {
    'name':'lucy',
    'score':90
}
dic2 = {
    'name':' mery',
    'score':87
}
l1 = [dic1, dic2]
pd. DataFrame(data=l1)

    name  score
0   lucy     90
1   mery     87

4. DataFrame.from_dict()函数构造

In [286]:
names = ['lucy', 'mery', 'tom', 'alex', '智哥']
yuwen =np.random.randint(0,100,size=5)
shuxue = np.random.randint(0,100, size=5)
display(names, yuwen, shuxue)

['lucy', 'mery', 'tom', 'alex', '智哥']

array([32, 11, 40, 71, 24], dtype=int32)

array([ 0, 17,  6, 87, 62], dtype=int32)

In [287]:
dictionary = {
    'names' : names,
    '语文' : yuwen,
    '数学' : shuxue
}

score = pd.DataFrame(data=dictionary)

### 1.3.2 DataFrame属性

- dtypes
- values
- index
- columns

In [288]:
score

  names  语文  数学
0  lucy  32   0
1  mery  11  17
2   tom  40   6
3  alex  71  87
4    智哥  24  62

In [289]:
score.dtypes

names    object
语文        int32
数学        int32
dtype: object

In [290]:
# ndarray VS DataFrame
score.values

array([['lucy', 32, 0],
       ['mery', 11, 17],
       ['tom', 40, 6],
       ['alex', 71, 87],
       ['智哥', 24, 62]], dtype=object)

In [291]:
score.index

RangeIndex(start=0, stop=5, step=1)

In [292]:
score.columns

Index(['names', '语文', '数学'], dtype='object')

### 1.3.3 DataFrame运算

1. 与非pandas对象运算

In [293]:
df = pd.DataFrame(data=np.random.randint(0,10, size=(3,4)),columns=list ('ABCD'))
df

   A  B  C  D
0  7  4  5  0
1  6  2  0  1
2  1  4  0  5

In [294]:
df + 10

    A   B   C   D
0  17  14  15  10
1  16  12  10  11
2  11  14  10  15

In [295]:
arr1 = np.array([1,2,3,4])
arr1

array([1, 2, 3, 4])

In [296]:
df + arr1

   A  B  C  D
0  8  6  8  4
1  7  4  3  5
2  2  6  3  9

In [297]:
arr2 = arr1.reshape((2,2)).copy()

In [298]:
# df + arr2

2. 与Series对象运算

In [299]:
s = pd.Series(data=[1,2,3], index=[0,1,2])
s

0    1
1    2
2    3
dtype: int64

In [300]:
df

   A  B  C  D
0  7  4  5  0
1  6  2  0  1
2  1  4  0  5

In [301]:
# DataFrame和Series运算，默认就是列索引对其原则
df + s

    A   B   C   D   0   1   2
0 NaN NaN NaN NaN NaN NaN NaN
1 NaN NaN NaN NaN NaN NaN NaN
2 NaN NaN NaN NaN NaN NaN NaN

In [302]:
df.add(s, axis='index')

   A  B  C  D
0  8  5  6  1
1  8  4  2  3
2  4  7  3  8

3. 与DataFrame对象运算

- 索引对齐原则(rowcolumns)

- 对不齐补空值，使用add\sub\mul\div函数处理空值

Python操作符与pandas操作函数的对应表：

| Python Operator | Pandas Method(s) |
| --- | --- |
| + | add() |
| - | sub(), subtract() |
| * | mul(), multiply() |
| / | truediv(), div(), divide() |
| // | floordiv() |
| % | mod() |
| ** | pow() |

In [303]:
df1 = pd.DataFrame(data=np.random.randint(0, 10, size=(3, 3)), columns=list('ABC'))
df2 = pd.DataFrame(data=np.random.randint(0, 10, size=(2, 2)), columns=list('BA'))
display(df1, df2)

   A  B  C
0  2  8  0
1  8  5  1
2  5  6  5

   B  A
0  4  2
1  1  3

In [304]:
df1 + df2

      A     B   C
0   4.0  12.0 NaN
1  11.0   6.0 NaN
2   NaN   NaN NaN

In [305]:
# fill_value不支持DataFrame和Series之间的运算
df1.add(df2, fill_value=0)

      A     B    C
0   4.0  12.0  0.0
1  11.0   6.0  1.0
2   5.0   6.0  5.0

4. NumPy functions

In [306]:
arr = np.random.randint(-10, 10, size=(3, 3))
arr

array([[  8, -10,   8],
       [  9,   5,  -3],
       [ -7,   0, -10]], dtype=int32)

In [307]:
df = pd.DataFrame(data=arr)
df

   0   1   2
0  8 -10   8
1  9   5  -3
2 -7   0 -10

In [308]:
np.abs(df)

   0   1   2
0  8  10   8
1  9   5   3
2  7   0  10

5. 转置运算

In [309]:
df

   0   1   2
0  8 -10   8
1  9   5  -3
2 -7   0 -10

In [310]:
df.T

    0  1   2
0   8  9  -7
1 -10  5   0
2   8 -3 -10

## 1.4 Pandas访问

In [311]:
arr = np.random.randint(0, 10, size=(5))
arr

array([5, 7, 7, 5, 9], dtype=int32)

In [312]:
arr > 2

array([ True,  True,  True,  True,  True])

In [313]:
ndarray[ndim1_index, ndim2_index...]

ndim_index: 索引、索引列表、BOOL、切片、条件表达式

SyntaxError: invalid character '、' (U+3001) (2739748058.py, line 3)

In [ ]:
arr2 = np.random.randint(0, 10, size=(5, 6))
arr2

array([[7, 7, 7, 0, 0, 3],
       [5, 0, 3, 3, 0, 3],
       [5, 9, 3, 8, 1, 0],
       [2, 0, 4, 6, 8, 2],
       [2, 8, 3, 3, 8, 7]], dtype=int32)

In [ ]:
arr2[2, 1] = 100
arr2

array([[  7,   7,   7,   0,   0,   3],
       [  5,   0,   3,   3,   0,   3],
       [  5, 100,   3,   8,   1,   0],
       [  2,   0,   4,   6,   8,   2],
       [  2,   8,   3,   3,   8,   7]], dtype=int32)

In [ ]:
df = pd.DataFrame(data=arr2, columns=list('ABCDEF'))
df

   A    B  C  D  E  F
0  7    7  7  0  0  3
1  5    0  3  3  0  3
2  5  100  3  8  1  0
3  2    0  4  6  8  2
4  2    8  3  3  8  7

In [ ]:
df.values

array([[  7,   7,   7,   0,   0,   3],
       [  5,   0,   3,   3,   0,   3],
       [  5, 100,   3,   8,   1,   0],
       [  2,   0,   4,   6,   8,   2],
       [  2,   8,   3,   3,   8,   7]], dtype=int32)

### 1.4.1 Basics标准访问形式

| Object Type | Indexers |
| :--- | :--- |
| Series | s.loc[indexer] |
| DataFrame | df.loc[row_indexer, column_indexer] |

loc[] 显示访问:在pandas对象中，可以使用标签的形式访问数据

iloc[] 隐式访问:在pandas对象中，也可以使用index的形式访问数据

In [ ]:
df

   A    B  C  D  E  F
0  7    7  7  0  0  3
1  5    0  3  3  0  3
2  5  100  3  8  1  0
3  2    0  4  6  8  2
4  2    8  3  3  8  7

### 1.4.2 使用Labels访问loc[] 显示访问

In [ ]:
s = pd.Series(data=np.array([True, False, True]),index=list('ABC'))

In [ ]:
l1 = [1,2,3,4,5,6]

l1[-2:]

[5, 6]

In [ ]:
s

A     True
B    False
C     True
dtype: bool

In [ ]:
s['A': "B"]

A     True
B    False
dtype: bool

> tips:使用索引切片的都是左闭右开，使用标签切片的都是闭合区间

s.loc[labels]

df.loc[row_labels, column_labels]

labels: 标签名， 标签名列表， BOOL列表（没有标签的，有标签），条件表达式，切片

In [ ]:
df

   A    B  C  D  E  F
0  7    7  7  0  0  3
1  5    0  3  3  0  3
2  5  100  3  8  1  0
3  2    0  4  6  8  2
4  2    8  3  3  8  7

In [ ]:
df.loc[0, 'A']

np.int32(7)

In [ ]:
df.loc[0]

A    7
B    7
C    7
D    0
E    0
F    3
Name: 0, dtype: int32

In [ ]:
df.loc[:,['A', 'B']]

   A    B
0  7    7
1  5    0
2  5  100
3  2    0
4  2    8

In [ ]:
df.loc[[1,2], ['B', 'C']]

     B  C
1    0  3
2  100  3

In [ ]:
df.loc[np.array([True, True, False, False, False])]

   A  B  C  D  E  F
0  7  7  7  0  0  3
1  5  0  3  3  0  3

In [ ]:
bool_list = pd.Series(data=np.array([True, True, False, False, False]), index=[0,4,1,2,3])
bool_list

0     True
4     True
1    False
2    False
3    False
dtype: bool

In [ ]:
df.loc[bool_list]

   A  B  C  D  E  F
0  7  7  7  0  0  3
4  2  8  3  3  8  7

In [ ]:
df.loc[:, bool_list.values]

IndexError: Boolean index has wrong length: 5 instead of 6

In [ ]:
s=pd.Series(data=np.random.randint(0, 10, size=5), index=list('abcde'))
s

a    4
b    4
c    3
d    4
e    8
dtype: int32

In [ ]:
s.loc['b':'c']

b    4
c    3
dtype: int32

In [ ]:
s.loc[['b', 'c']]

b    4
c    3
dtype: int32

In [ ]:
s.loc[[False, True, True, False, False]]

b    4
c    3
dtype: int32

In [ ]:
s.loc[s > 6]

e    8
dtype: int32

### 1.4.3 使用indexer隐示访问 iloc[]

In [ ]:
s.iloc[index]
df.iloc[row_index, col_index]
index: index, index_list, bool_list, 条件表达式，切片（左闭右开）

SyntaxError: invalid character '，' (U+FF0C) (3010730578.py, line 3)

In [ ]:
df.loc[:, 'A']

0    7
1    5
2    5
3    2
4    2
Name: A, dtype: int32

In [ ]:
df.iloc[:, 0]

0    7
1    5
2    5
3    2
4    2
Name: A, dtype: int32

In [ ]:
df.iloc[[True, False, True, False, False, False]]

IndexError: Boolean index has wrong length: 6 instead of 5

In [ ]:
# iloc访问，是左闭右开区间
df.iloc[0:3]

   A    B  C  D  E  F
0  7    7  7  0  0  3
1  5    0  3  3  0  3
2  5  100  3  8  1  0

In [ ]:
# loc访问，显示访问，闭合区间
df.loc[0:2]

   A    B  C  D  E  F
0  7    7  7  0  0  3
1  5    0  3  3  0  3
2  5  100  3  8  1  0

### 1.4.4 间接访问

In [ ]:
df.loc[0].loc['B'] = 10

C:\Users\songlk2\AppData\Local\Temp\ipykernel_27420\2967821122.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df.loc[0].loc['B'] = 10

In [ ]:
df.loc[0, 'B']

np.int32(10)

In [ ]:
df.loc[:,'B'].iloc[2]

np.int32(100)

注意：直接用中括号访问

标签访问的是列

标签切片的是行

In [ ]:
# 把dataframe当字典，列索引就是字典的键，所以可以直接通过[列标签]形式访问列df['A']
df['A']

0    7
1    5
2    5
3    2
4    2
Name: A, dtype: int32

In [ ]:
df[['A', 'B']]

   A    B
0  7   10
1  5    0
2  5  100
3  2    0
4  2    8

In [ ]:
df.loc[:, ['A', 'B']]

   A    B
0  1   10
1  7    6
2  1  100
3  7    0
4  4    1

### 1.4.5 where() and mask()

where:满足con条件的保留，其他用other填充

mask:不满足con条件的保留，其他用other填充

In [ ]:
df = pd.DataFrame(data=np.random.randint(0,100,size=(5,4)), columns=list('ABCD'))
df

    A   B   C   D
0  83  80   8  79
1   7  73  29  13
2  16  78   3  54
3   8  95  67  66
4  75   4  46  48

In [ ]:
df > 60

       A      B      C      D
0   True   True  False   True
1  False   True  False  False
2  False   True  False  False
3  False   True   True   True
4   True  False  False  False

In [ ]:
condition = df > 60

In [ ]:
condition = df['A'] > 60

In [ ]:
df.where(cond=df > 60, other='不及格')

     A    B    C    D
0   83   80  不及格   79
1  不及格   73  不及格  不及格
2  不及格   78  不及格  不及格
3  不及格   95   67   66
4   75  不及格  不及格  不及格

In [ ]:
df.where(cond=df['A'] > 60, other='其他')

    A   B   C   D
0  83  80   8  79
1  其他  其他  其他  其他
2  其他  其他  其他  其他
3  其他  其他  其他  其他
4  75   4  46  48

In [ ]:
df.where(cond=df>60,other=pd.Series(data=[100,200],index=['A','B']),axis=1)

     A    B     C     D
0   83   80   NaN  79.0
1  100   73   NaN   NaN
2  100   78   NaN   NaN
3  100   95  67.0  66.0
4   75  200   NaN   NaN

In [ ]:
df.where(cond=df>60,other=pd.Series(data=[100,200],index=[1,2]),axis=0)

       A     B      C      D
0   83.0  80.0    NaN   79.0
1  100.0  73.0  100.0  100.0
2  200.0  78.0  200.0  200.0
3    NaN  95.0   67.0   66.0
4   75.0   NaN    NaN    NaN

In [ ]:
df.mask(cond=df > 60,other='及格')

    A   B   C   D
0  及格  及格   8  及格
1   7  及格  29  13
2  16  及格   3  54
3   8  及格  及格  及格
4  及格   4  46  48

In [ ]:
df.mask(cond=df > 60, other=pd.Series(data=[100, 200, 300, 400], index=['A','B', 'C', 'D']), axis=1)

     A    B    C    D
0  100  200    8  400
1    7  200   29   13
2   16  200    3   54
3    8  200  300  400
4  100    4   46   48

### 1.4.6 The query() Method

In [ ]:
df.query('A > 60')

    A   B   C   D
0  83  80   8  79
4  75   4  46  48

In [ ]:
df.query('A > 60 and B > 60')

    A   B  C   D
0  83  80  8  79

### 1.4.7 The filter() Method

对行名和列名进行筛选

In [ ]:
df.columns = ['AA', 'BB', 'CB', 'DB']
df

   AA  BB  CB  DB
0  83  80   8  79
1   7  73  29  13
2  16  78   3  54
3   8  95  67  66
4  75   4  46  48

In [ ]:
df.filter(items=['AA', 'BB'])

   AA  BB
0  83  80
1   7  73
2  16  78
3   8  95
4  75   4

使用items选择行、列名称，配合axis

In [ ]:
df[['AA', 'BB']]

   AA  BB
0  83  80
1   7  73
2  16  78
3   8  95
4  75   4

In [ ]:
df.filter(items=[0, 1], axis=0)

   AA  BB  CB  DB
0  83  80   8  79
1   7  73  29  13

使用regex正则表达式，模糊匹配名称

In [ ]:
df.filter(regex='.*B.*', axis=1)

   BB  CB  DB
0  80   8  79
1  73  29  13
2  78   3  54
3  95  67  66
4   4  46  48

In [ ]:
df.filter(regex='^B',axis=1)

   BB
0  80
1  73
2  78
3  95
4   4

## 1.5 聚合函数

| 函数 (Function) | 描述 (Description) | 中文说明 |
| :--- | :--- | :--- |
| count | Number of non-NA observations | 个数 |
| sum | Sum of values | 求和 |
| mean | Mean of values | 均值 |
| mad | Mean absolute deviation | 绝对值均值 |
| median | Arithmetic median of values | 中位数 |
| min | Minimum | 最小值 |
| max | Maximum | 最大值 |
| mode | Mode | 众数 |
| abs | Absolute Value | 绝对值 |
| prod | Product of values | 乘积 |
| std | Bessel-corrected sample standard deviation | 标准差 |
| var | Unbiased variance | 方差 |
| quantile | Sample quantile (value at %) | 分位数 |
| cumsum | Cumulative sum | 累和 |
| cumprod | Cumulative product | 累积 |

In [ ]:
arr1 = df.values

In [ ]:
arr1

array([[83, 80,  8, 79],
       [ 7, 73, 29, 13],
       [16, 78,  3, 54],
       [ 8, 95, 67, 66],
       [75,  4, 46, 48]], dtype=int32)

In [ ]:
arr1.sum(axis=1)

array([250, 122, 151, 236, 173])

In [ ]:
arr1.mean(axis=0)

array([37.8, 66. , 30.6, 52. ])

In [ ]:
arr1

array([[83, 80,  8, 79],
       [ 7, 73, 29, 13],
       [16, 78,  3, 54],
       [ 8, 95, 67, 66],
       [75,  4, 46, 48]], dtype=int32)

In [ ]:
arr1 = arr1.astype(np.float32)

In [ ]:
arr1

array([[83., 80.,  8., 79.],
       [ 7., 73., 29., 13.],
       [16., 78.,  3., 54.],
       [ 8., 95., 67., 66.],
       [75.,  4., 46., 48.]], dtype=float32)

In [ ]:
arr1[1,1] = np.nan

In [ ]:
arr1.sum()

np.float32(nan)

In [ ]:
np.nansum(arr1)

np.float32(859.0)

In [ ]:
df.loc[1, 'BB'] = np.nan

In [ ]:
df

   AA    BB  CB  DB
0  83  80.0   8  79
1   7   NaN  29  13
2  16  78.0   3  54
3   8  95.0  67  66
4  75   4.0  46  48

In [ ]:
# DataFrame默认是列方向的聚合
# pandas自动忽略空值
df.sum()

AA    189.0
BB    257.0
CB    153.0
DB    260.0
dtype: float64

In [ ]:
df.sum(axis=1)

0    250.0
1     49.0
2    151.0
3    236.0
4    173.0
dtype: float64

In [ ]:
np.nansum(df.values)

np.float64(859.0)

In [ ]:
df.sum()

AA    189.0
BB    257.0
CB    153.0
DB    260.0
dtype: float64

## 1.6 习题

背景：假设班级有张三、李四、王五、赵六四位同学，考试要考的科目有Python、Java、C

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
index=['张三','李四','王五','赵六']
columns=['Python','Java','C']
score1 = pd.DataFrame(data=np.random.randint(0,100,size=(4,3)),index=index,columns=columns)
score2 = pd.DataFrame(data=np.random.randint(0,100,size=(4,3)),index=index,columns=columns)

In [ ]:
display(score1,score2)

    Python  Java   C
张三      40    16  82
李四      54    91  91
王五       6    11  63
赵六      11    45  39

    Python  Java   C
张三      13    68  28
李四      65    70  10
王五      80    47  38
赵六      81    35  29

1.假设score1是中期考试成绩，score2是期末考试成绩，请自由创建score1和score2，并将其相加，求出期末平均值。

In [ ]:
(score1 + score2) / 2

    Python  Java     C
张三    26.5  42.0  55.0
李四    59.5  80.5  50.5
王五    43.0  29.0  50.5
赵六    46.0  40.0  34.0

2.假设三期考试前Java没发现作弊，要记为0分，如何实现？

In [ ]:
score1.loc['张三', 'Java'] = 0

In [ ]:
score1

    Python  Java   C
张三      40     0  82
李四      54    91  91
王五       6    11  63
赵六      11    45  39

3.李四因为举报张三作弊成功，期中考试所有科目加10分，如何实现？

In [ ]:
score1.loc['李四'] += 10

In [ ]:
score1

    Python  Java    C
张三      40     0   82
李四      64   101  101
王五       6    11   63
赵六      11    45   39

4.由于有一道题出错，要给所有学生加10分，如何实现？

In [ ]:
score1 = score1 + 10

In [ ]:
score1

    Python  Java    C
张三      50    10   92
李四      74   111  111
王五      16    21   73
赵六      21    55   49

5.Python老师想知道哪些同学的Java成绩比Python好，如何实现？

In [ ]:
cond = score1['Python'] < score1['Java']
cond

张三    False
李四     True
王五     True
赵六     True
dtype: bool

In [ ]:
score1.loc[cond].index

Index(['李四', '王五', '赵六'], dtype='object')

## 1.7 单层索引和多层级索引

In [ ]:
df = pd.DataFrame(data=np.random.randint(0, 10, size=(5, 3)), columns=list('ABC'))

In [ ]:
df

   A  B  C
0  9  7  3
1  3  8  0
2  8  3  3
3  3  9  3
4  2  6  5

In [ ]:
df.index = list('abcde')

In [ ]:
df

   A  B  C
a  9  7  3
b  3  8  0
c  8  3  3
d  3  9  3
e  2  6  5

In [ ]:
df.cloumns = [1, 2, 3]

C:\Users\songlk2\AppData\Local\Temp\ipykernel_25252\397525377.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df.cloumns = [1, 2, 3]

In [ ]:
df

   A  B  C
a  9  7  3
b  3  8  0
c  8  3  3
d  3  9  3
e  2  6  5

In [ ]:
pd.Index(data=[1,2,3])

Index([1, 2, 3], dtype='int64')

In [ ]:
m_index = pd.RangeIndex(start=0, stop=5, step=1, name='index')

In [ ]:
np.arange(0, 10, step=1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
df.index = m_index

In [ ]:
df

       A  B  C
index
0      9  7  3
1      3  8  0
2      8  3  3
3      3  9  3
4      2  6  5

In [ ]:
for i in m_index:
    print(i)

0
1
2
3
4

In [ ]:
temp = pd.CategoricalIndex(data=[1,2,3,4])

In [ ]:
temp[-1]

np.int64(4)

怎么使用索引:

pd.Index是pandas提供的专门用手构造索引的类，它有很多子类，CategoricalIndex，RangeIndex，Int64Index，Float64Index，MultiIndex，PeriodIndex，DatetimeIndex，TimedeltaIndex，IntervalIndex，UInt64Index，CategoricalIndex等等

所有的子类都具备Index类的特点，比如可以使用索引访问元素

通常如果需要对索引定制(name),可以使用pd.Index系列方法来构造索引

如果没有特殊需求，使用普通的列表完全没有问题

### 1.7.1 单层索引

使用pd.Index()

### 1.7.2 多层索引构造

使用arrays pd.Multindex.from_arrays()

In [ ]:
LEVEL1 = ['第一期', '第二期']
LEVEL2 = ['A', 'B', 'C']

In [ ]:
df.index

MultiIndex([('第一期', 'lucy'),
            ('第一期',  'tom'),
            ('第一期', 'alex'),
            ('第二期', 'lucy'),
            ('第二期',  'tom'),
            ('第二期', 'alex')],
           )

In [ ]:
columns = pd.MultiIndex.from_arrays([['第一期', '第一期', '第一期', '第二期', '第二期', '第二期'], ['lucy', 'tom', 'alex', 'lucy', 'tom', 'alex']])
index = list('ABC')
data = np.random.randint(0, 100, size=(3, 6))
pd.DataFrame(data=data, index=index, columns=columns)
# [["第一期", '第一期', '第一期', '第二期', '第二期', '第二期'], ['lucy', 'tom', 'alex', 'lucy', 'tom', 'alex']]
#可以直接作为多层索引使用，不需要构造MultiIndex对象
# pd.MultiIndex.from_arrays(必须是一个如上的二维数组结构)
# 麻烦，不采用，了解即可

   第一期           第二期
  lucy tom alex lucy tom alex
A   20  33   91   91  58    4
B   18   1   84   10  93   88
C   54  52   67   71  87   83

使用tuple pd.Multilndex,from_tuples

In [ ]:
tuples= pd.MultiIndex.from_tuples([('第一期','lucy'),('第一期','tom'),('第一期','alex'),('第二期','lucy'),('第二期','tom'),('第二期','alex')])
index=list('ABC')
data=np.random.randint(0, 100, size=(3,6))
pd.DataFrame(data=data,index=index,columns=tuples)

   第一期           第二期
  lucy tom alex lucy tom alex
A   67  64   25   28  38   31
B   18  64   68    1  18   45
C   66  77   58   13  13   59

使用product pd.Multilndex.from_product

In [ ]:
columns = pd.MultiIndex.from_product([LEVEL1, LEVEL2], names=['期数', '产品'])

In [ ]:
index = pd.Index(data=['lucy', 'tom', 'alex'], name='销售员')

In [ ]:
data = np.random.randint(0,100,size=(3,6))

In [ ]:
df = pd.DataFrame(data=data, index=index, columns=columns)
df

期数   第一期         第二期
产品     A   B   C   A   B   C
销售员
lucy  79  99  42  74  19  95
tom   25  59   0  68  41  51
alex  26  99  83  81  47  80

In [317]:
index = pd.MultiIndex.from_product([['第一期', '第二期'], ['lucy', 'tom', 'alex']])
columns = ['A', 'B', 'C']
data=np.random.randint(0, 100, size=(6,3))
df = pd.DataFrame(data=data, index=index, columns=columns)
df

           A   B   C
第一期 lucy  89  51  72
    tom   37  70  70
    alex  39  62  53
第二期 lucy  47  67  99
    tom   39  96  96
    alex  90  58  93

### 1.7.3 多层索引访问

In [318]:
df

           A   B   C
第一期 lucy  89  51  72
    tom   37  70  70
    alex  39  62  53
第二期 lucy  47  67  99
    tom   39  96  96
    alex  90  58  93

In [319]:
df.loc[:, 'A']

第一期  lucy    89
     tom     37
     alex    39
第二期  lucy    47
     tom     39
     alex    90
Name: A, dtype: int32

In [320]:
df.loc[:, ['A', 'B']]

           A   B
第一期 lucy  89  51
    tom   37  70
    alex  39  62
第二期 lucy  47  67
    tom   39  96
    alex  90  58

In [321]:
df.loc[:, 'A':'B']

           A   B
第一期 lucy  89  51
    tom   37  70
    alex  39  62
第二期 lucy  47  67
    tom   39  96
    alex  90  58

In [322]:
df

           A   B   C
第一期 lucy  89  51  72
    tom   37  70  70
    alex  39  62  53
第二期 lucy  47  67  99
    tom   39  96  96
    alex  90  58  93

In [323]:
df.index

MultiIndex([('第一期', 'lucy'),
            ('第一期',  'tom'),
            ('第一期', 'alex'),
            ('第二期', 'lucy'),
            ('第二期',  'tom'),
            ('第二期', 'alex')],
           )

In [324]:
df.loc[('第一期', 'alex')]

A    39
B    62
C    53
Name: (第一期, alex), dtype: int32

In [325]:
df.loc[[('第一期', 'alex'), ('第二期', 'alex')]]

           A   B   C
第一期 alex  39  62  53
第二期 alex  90  58  93

In [326]:
df.sort_index().loc[('第一期', 'alex'):('第二期', 'alex')]

           A   B   C
第一期 alex  39  62  53
    lucy  89  51  72
    tom   37  70  70
第二期 alex  90  58  93

总结:

多层索引的访问逻辑，与单层索引的访问逻完全一致

但是，多层索引的索引表达形式是以元组的方式处理的

In [327]:
df.loc['第一期']

       A   B   C
lucy  89  51  72
tom   37  70  70
alex  39  62  53

In [328]:
#可以从外层索引开始，一级一级的向内层访问，但是不能越级访问
df.loc['第一期'].loc['alex']

A    39
B    62
C    53
Name: alex, dtype: int32

In [329]:
# 切片要先将索引进行从小到大的排序 df.sort_index()
# 切片 索引必须要先排序

使用labels

In [330]:
df.sort_index().loc[('第一期','alex'):('第二期','alex')]

           A   B   C
第一期 alex  39  62  53
    lucy  89  51  72
    tom   37  70  70
第二期 alex  90  58  93

In [331]:
df

           A   B   C
第一期 lucy  89  51  72
    tom   37  70  70
    alex  39  62  53
第二期 lucy  47  67  99
    tom   39  96  96
    alex  90  58  93

隐式

使用index

In [332]:
df.iloc[0:4]

           A   B   C
第一期 lucy  89  51  72
    tom   37  70  70
    alex  39  62  53
第二期 lucy  47  67  99

In [333]:
df.iloc[0]

A    89
B    51
C    72
Name: (第一期, lucy), dtype: int32

In [334]:
df.iloc[[0, 1]]

           A   B   C
第一期 lucy  89  51  72
    tom   37  70  70

## 1.8 Stack和Unstack

In [339]:
# unstack把行索引向列索引变换
# stack把列索引向行索引变换
df.unstack(level=1).unstack().unstack()

        第一期  第二期
A alex   39   90
  lucy   89   47
  tom    37   39
B alex   62   58
  lucy   51   67
  tom    70   96
C alex   53   93
  lucy   72   99
  tom    70   96

### 1.8.1 练习

1.创建一个DataFrame，表示出lucy, tom, jack期中期末各科(python, java, c)成绩

In [ ]:
data = np. random. randint(0, 100, size=(3,3))
index = pd. Index(data=['lucy','tom','jack'], name='姓名')
columns = pd. Index(data=['python','java','c'], name='学科')
score = pd. DataFrame(data=data, index=index, columns=columns)
score

2.获取学习成绩lucy成绩的最高分是哪门学科

In [ ]:
data1 = np.random.randint(0, 100, size=(3,3))
data2 = np.random.randint(0, 100, size=(3,3))
index = pd. Index(data=['lucy','tom','jack'], name='姓名')
columns = pd. Index(data=['python','java','c'], name='学科')
score1 = pd. DataFrame(data=data, index=index, columns=columns)
score2 = pd. DataFrame(data=data, index=index, columns=columns)

In [342]:
display(score1, score2)

学科    python  java   c
姓名
lucy      88    77  11
tom        8    12  22
jack      65    47  79

学科    python  java   c
姓名
lucy      88    77  11
tom        8    12  22
jack      65    47  79

In [343]:
score1.loc['lucy'].max()

88

In [345]:
score1.loc['lucy'] == score1.loc['lucy'].max()

学科
python     True
java      False
c         False
Name: lucy, dtype: bool

In [353]:
# 使用此结构访问 数据 df.loc[row_lables, col_labels]
# row_labels 就是 'lucy'
# col_labels 就是 score1.loc['lucy'] == score1.loc['lucy'].max() 返回一个BOOL值
score1.loc['lucy', score1.loc['lucy'] == score1.loc['lucy'].max()]

学科
python    88
Name: lucy, dtype: int32

In [354]:
score1

学科    python  java   c
姓名
lucy      88    77  11
tom        8    12  22
jack      65    47  79

3.同时获取上学期和下学期的成绩，计算python的各学科的平均成绩

In [ ]:
# 使用一个多层级索引来表达数据
columns = pd.MultiIndex.from_product([['上学期', '下学期'], ['java', 'python', 'c']])
index = ['lucy', 'tom', 'jack']
data = np.random.randint(0, 100, size=(3,6))
score = pd.DataFrame(data=data, index=index, columns=columns)
score

      上学期             下学期
     java python   c java python   c
lucy   92     19   0   42     27  21
tom    76     61  64   70     48  99
jack   81     29  13   57     63  69

In [356]:
score.loc['tom']

上学期  java      76
     python    61
     c         64
下学期  java      70
     python    48
     c         99
Name: tom, dtype: int32

In [357]:
tom_score = score.loc['tom']
tom_score.unstack().mean()

c         81.5
java      73.0
python    54.5
dtype: float64

4.获取学习成绩jack的python成绩，并把他改为20分

In [366]:
score.loc['jack', ('上学期', 'python')] += 20

In [367]:
score

      上学期             下学期
     java python   c java python   c
lucy   92     19   0   42     27  21
tom    76     61  64   70     48  99
jack   81     69  13   57     63  69

In [368]:
score1 = score.unstack(level=2).unstack(level=2).stack(level=-1)

In [369]:
score1

上学期  c       lucy     0
             tom     64
             jack    13
     java    lucy    92
             tom     76
             jack    81
     python  lucy    19
             tom     61
             jack    69
下学期  c       lucy    21
             tom     99
             jack    69
     java    lucy    42
             tom     70
             jack    57
     python  lucy    27
             tom     48
             jack    63
dtype: int32