# 1 Pandas数据处理

In [2]:
import pandas as pd
import numpy as np

## 1.1 数据IO操作

In [3]:
fp = open('csv文件.csv', 'r', encoding='utf-8')
fp.read()	I
fp.close()

SyntaxError: invalid syntax (2260919051.py, line 2)

In [ ]:
with open('csv文件.csv','r',encoding='utf-8')as fp:
    fp.read()

pandas IO操作主要是读取有特定格式的文件

pd.read_csv()

In [ ]:
pd.read_csv('csv文件.csv', sep=',', header=None, index_col=0)

       1   2
0
lucy  19  北京
mery  20  上海
tom   22  北京

pd.read_table()

In [ ]:
pd.read_table('txt文件.txt', header=None, sep=' ', index_col=0)

       1   2
0
lucy  19  北京
mery  20  上海
tom   22  北京

In [ ]:
pd.read_csv('txt文件.txt', sep=' ', header=None)

      0   1   2
0  lucy  19  北京
1  mery  20  上海
2   tom  22  北京

excel读取

In [ ]:
data = pd.read_excel('excel文件.xlsx', header=None, names=['姓名','年龄','地址'], sheet_name=0)

In [ ]:
data.to_excel('m_data.xlsx')

In [ ]:
data.to_csv('m_data.csv')

## 1.2 数据探索

- describe()
- info()
- head()
- tail()
- sample()

In [5]:
df = pd.DataFrame(data = np.random.randint(0, 10000, size=(10000, 4)), columns= list('ABCD'))
df

         A     B     C     D
0      570  4076  7821  3940
1     6433  6150  9021   316
2     4715  4648  9895  3865
3     1471  8298  4390  1922
4     3206  3190  8210  7584
...    ...   ...   ...   ...
9995  3538  7813  3994  5689
9996  7042  5710  6084  9290
9997  8393  8921  4176  4662
9998  7192   282  1442  7277
9999  2301  1660  6413  5629

[10000 rows x 4 columns]

In [6]:
df.describe(percentiles=[0.25,0.75,0.99])

                  A             B             C             D
count  10000.000000  10000.000000  10000.000000  10000.000000
mean    5007.441400   4999.556300   5004.446300   4965.664100
std     2899.354023   2912.123119   2895.467075   2886.516964
min        3.000000      3.000000      0.000000      0.000000
25%     2470.000000   2432.750000   2475.500000   2468.000000
50%     4998.500000   4997.500000   5003.000000   4926.500000
75%     7536.000000   7560.250000   7512.000000   7450.250000
99%     9897.010000   9893.000000   9908.010000   9914.030000
max     9998.000000   9999.000000   9999.000000   9999.000000

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       10000 non-null  int32
 1   B       10000 non-null  int32
 2   C       10000 non-null  int32
 3   D       10000 non-null  int32
dtypes: int32(4)
memory usage: 156.4 KB

In [8]:
df.head()

      A     B     C     D
0   570  4076  7821  3940
1  6433  6150  9021   316
2  4715  4648  9895  3865
3  1471  8298  4390  1922
4  3206  3190  8210  7584

In [10]:
df.tail(n=2)

         A     B     C     D
9998  7192   282  1442  7277
9999  2301  1660  6413  5629

In [11]:
df.sample(n=10)

         A     B     C     D
860   9746  9417  1782  1687
1659  9918  3328   983  7174
7979  6424  8226  2189  3538
1558  1762  9114  1934   610
7919  6894   374  7212  1614
2965  7383  1735  9669  9194
8109  3128  5703  4463  8108
2705  8383  2724   423  3516
3500  7354  9579  2968  6056
7358  9363  3043  6946  8606

## 1.3 空值处理

In [14]:
type(None)

NoneType

In [16]:
type(np.nan)

float

In [17]:
def get_sum(x):
    return x.sum()

In [18]:
data1 = np.arange(100000, dtype=object)

In [20]:
%timeit get_sum(data1)

2.55 ms ± 71.1 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [22]:
data2 = np.arange(100000, dtype=np.float64)

In [23]:
%timeit get_sum(data2)

34 μs ± 388 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

object 运算效率 低于float

### 1.3.1 None

None是Python自带的，其类型为python object。因此，None不能参与到任何计算中。

object类型的运算要比int类型的运算慢得多

### 1.3.2 np.nan（NaN）

np.nan是浮点类型，能参与到计算中，但计算的结果总是NaN。

在numpy中，可以使用np.nanxxx()函数来计算nan，此时视nan为0。

### 1.3.3 pandas自动把None处理成np.nan

In [26]:
df = pd.DataFrame(data=np.random.randint(0, 10, size=(10,2)), columns=['A', 'B'])
df

   A  B
0  7  2
1  1  9
2  2  9
3  9  4
4  9  3
5  7  4
6  1  7
7  0  4
8  1  3
9  1  9

In [27]:
df.loc[2] = None

In [29]:
# numpy 提供第一个常量，用于表达空值，是一个float
# NaN(not a number) 符号，不是一个量，pandas对象中，所有的np.nan None 显示的时候，都是以NaN显示
# NaT(not a time)
np.nan

nan

In [30]:
a = np.nan

In [28]:
df

     A    B
0  7.0  2.0
1  1.0  9.0
2  NaN  NaN
3  9.0  4.0
4  9.0  3.0
5  7.0  4.0
6  1.0  7.0
7  0.0  4.0
8  1.0  3.0
9  1.0  9.0

In [32]:
df.loc[2, 'A'] # np.nan

np.float64(nan)

In [33]:
df

     A    B
0  7.0  2.0
1  1.0  9.0
2  NaN  NaN
3  9.0  4.0
4  9.0  3.0
5  7.0  4.0
6  1.0  7.0
7  0.0  4.0
8  1.0  3.0
9  1.0  9.0

In [35]:
l_data = [None, 1, 2, 3.14, 'str']

arr = np.array(l_data)

pd.Series(data=arr)

0    None
1       1
2       2
3    3.14
4     str
dtype: object

### 1.3.4 空值查找

isnull()

notnull()

In [37]:
df = pd.DataFrame(data=np.random.random(size=(10,4)), columns=list('ABCD'))
df

          A         B         C         D
0  0.960685  0.765729  0.482479  0.496986
1  0.056180  0.186704  0.560583  0.479668
2  0.552933  0.197549  0.771135  0.349525
3  0.306238  0.008593  0.496193  0.618088
4  0.782668  0.934488  0.156800  0.685145
5  0.831522  0.642916  0.089744  0.927833
6  0.440684  0.166032  0.356055  0.007285
7  0.467082  0.115364  0.128460  0.979708
8  0.878624  0.009373  0.023424  0.042076
9  0.862758  0.798626  0.277863  0.202602

In [38]:
df.loc[2] = np.nan
df.loc[4, 'B'] = np.nan
df.loc[5, 'D'] = np.nan
df.loc[9, ['A', 'B']] = np.nan
df

          A         B         C         D
0  0.960685  0.765729  0.482479  0.496986
1  0.056180  0.186704  0.560583  0.479668
2       NaN       NaN       NaN       NaN
3  0.306238  0.008593  0.496193  0.618088
4  0.782668       NaN  0.156800  0.685145
5  0.831522  0.642916  0.089744       NaN
6  0.440684  0.166032  0.356055  0.007285
7  0.467082  0.115364  0.128460  0.979708
8  0.878624  0.009373  0.023424  0.042076
9       NaN       NaN  0.277863  0.202602

In [42]:
# 查看一个bool列表中，是否存在至少一个True
np.array([False, False, False]).any()

np.False_

In [43]:
# 查看一个bool列表中，是否全为True
np.array([False, True, False]).all()

np.False_

In [46]:
df.isnull()

       A      B      C      D
0  False  False  False  False
1  False  False  False  False
2   True   True   True   True
3  False  False  False  False
4  False   True  False  False
5  False  False  False   True
6  False  False  False  False
7  False  False  False  False
8  False  False  False  False
9   True   True  False  False

In [44]:
# 默认列方向的any操作
df.isnull().any()

A    True
B    True
C    True
D    True
dtype: bool

In [45]:
df.isnull().any(axis=1)

0    False
1    False
2     True
3    False
4     True
5     True
6    False
7    False
8    False
9     True
dtype: bool

In [47]:
# 可以找出所有包含至少一个空值的hang
df.loc[df.isnull().any(axis=1)]

          A         B         C         D
2       NaN       NaN       NaN       NaN
4  0.782668       NaN  0.156800  0.685145
5  0.831522  0.642916  0.089744       NaN
9       NaN       NaN  0.277863  0.202602

In [49]:
# 找出所有至少包含一个空值的列？？

In [51]:
# 找出全都不为空的行
df.loc[df.notnull().all(axis=1)]

          A         B         C         D
0  0.960685  0.765729  0.482479  0.496986
1  0.056180  0.186704  0.560583  0.479668
3  0.306238  0.008593  0.496193  0.618088
6  0.440684  0.166032  0.356055  0.007285
7  0.467082  0.115364  0.128460  0.979708
8  0.878624  0.009373  0.023424  0.042076

True: 1

False: 0

In [53]:
# 查看某一【列】的空值占比
df.isnull().mean()

A    0.2
B    0.3
C    0.1
D    0.2
dtype: float64

列字段是不能轻易删除的

### 1.3.5 空值填充

fillna()

In [57]:
# 整个表格中的统一填充方法
df.fillna(value=0)

          A         B         C         D
0  0.960685  0.765729  0.482479  0.496986
1  0.056180  0.186704  0.560583  0.479668
2  0.000000  0.000000  0.000000  0.000000
3  0.306238  0.008593  0.496193  0.618088
4  0.782668  0.000000  0.156800  0.685145
5  0.831522  0.642916  0.089744  0.000000
6  0.440684  0.166032  0.356055  0.007285
7  0.467082  0.115364  0.128460  0.979708
8  0.878624  0.009373  0.023424  0.042076
9  0.000000  0.000000  0.277863  0.202602

In [61]:
# 使用均值来填充空值
df.mean()

A    0.590460
B    0.270673
C    0.285733
D    0.438945
dtype: float64

In [64]:
# 可以使用序列(Series)来批量填充，默认列索引对齐
df.fillna(value=df.mean())

          A         B         C         D
0  0.960685  0.765729  0.482479  0.496986
1  0.056180  0.186704  0.560583  0.479668
2  0.590460  0.270673  0.285733  0.438945
3  0.306238  0.008593  0.496193  0.618088
4  0.782668  0.270673  0.156800  0.685145
5  0.831522  0.642916  0.089744  0.438945
6  0.440684  0.166032  0.356055  0.007285
7  0.467082  0.115364  0.128460  0.979708
8  0.878624  0.009373  0.023424  0.042076
9  0.590460  0.270673  0.277863  0.202602

In [65]:
df

          A         B         C         D
0  0.960685  0.765729  0.482479  0.496986
1  0.056180  0.186704  0.560583  0.479668
2       NaN       NaN       NaN       NaN
3  0.306238  0.008593  0.496193  0.618088
4  0.782668       NaN  0.156800  0.685145
5  0.831522  0.642916  0.089744       NaN
6  0.440684  0.166032  0.356055  0.007285
7  0.467082  0.115364  0.128460  0.979708
8  0.878624  0.009373  0.023424  0.042076
9       NaN       NaN  0.277863  0.202602

In [69]:
values = df.mean(axis=1)
values

0    0.676470
1    0.320784
2         NaN
3    0.357278
4    0.541538
5    0.521394
6    0.242514
7    0.422653
8    0.238374
9    0.240232
dtype: float64

In [70]:
df.fillna(value=values, axis=1)

NotImplementedError: Currently only can fill with dict/Series column by column

In [71]:
df1 = df.T.copy()

In [72]:
df.fillna(value=df1.mean())

          A         B         C         D
0  0.960685  0.765729  0.482479  0.496986
1  0.056180  0.186704  0.560583  0.479668
2       NaN       NaN       NaN       NaN
3  0.306238  0.008593  0.496193  0.618088
4  0.782668       NaN  0.156800  0.685145
5  0.831522  0.642916  0.089744       NaN
6  0.440684  0.166032  0.356055  0.007285
7  0.467082  0.115364  0.128460  0.979708
8  0.878624  0.009373  0.023424  0.042076
9       NaN       NaN  0.277863  0.202602

In [73]:
df

          A         B         C         D
0  0.960685  0.765729  0.482479  0.496986
1  0.056180  0.186704  0.560583  0.479668
2       NaN       NaN       NaN       NaN
3  0.306238  0.008593  0.496193  0.618088
4  0.782668       NaN  0.156800  0.685145
5  0.831522  0.642916  0.089744       NaN
6  0.440684  0.166032  0.356055  0.007285
7  0.467082  0.115364  0.128460  0.979708
8  0.878624  0.009373  0.023424  0.042076
9       NaN       NaN  0.277863  0.202602

In [75]:
# 使用临近值填充
df.fillna(method='backfill', axis=1, limit=1)

C:\Users\songlk2\AppData\Local\Temp\ipykernel_35756\2611301585.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='backfill', axis=1, limit=1)

          A         B         C         D
0  0.960685  0.765729  0.482479  0.496986
1  0.056180  0.186704  0.560583  0.479668
2       NaN       NaN       NaN       NaN
3  0.306238  0.008593  0.496193  0.618088
4  0.782668  0.156800  0.156800  0.685145
5  0.831522  0.642916  0.089744       NaN
6  0.440684  0.166032  0.356055  0.007285
7  0.467082  0.115364  0.128460  0.979708
8  0.878624  0.009373  0.023424  0.042076
9       NaN  0.277863  0.277863  0.202602

### 1.3.6 空值过滤

dropna()

In [86]:
# 结合isnull notnull any all 来确定一个条件，然后再利用loc访问，实现过滤
df.loc[df.notnull().any(axis=1)]

          A         B         C         D
0  0.960685  0.765729  0.482479  0.496986
1  0.056180  0.186704  0.560583  0.479668
3  0.306238  0.008593  0.496193  0.618088
4  0.782668       NaN  0.156800  0.685145
5  0.831522  0.642916  0.089744       NaN
6  0.440684  0.166032  0.356055  0.007285
7  0.467082  0.115364  0.128460  0.979708
8  0.878624  0.009373  0.023424  0.042076
9       NaN       NaN  0.277863  0.202602

In [87]:
df.loc[df.notnull().all(axis=1)]

          A         B         C         D
0  0.960685  0.765729  0.482479  0.496986
1  0.056180  0.186704  0.560583  0.479668
3  0.306238  0.008593  0.496193  0.618088
6  0.440684  0.166032  0.356055  0.007285
7  0.467082  0.115364  0.128460  0.979708
8  0.878624  0.009373  0.023424  0.042076

In [88]:
# 过滤掉D列为空的数据
df.loc[df['D'].notnull()]

          A         B         C         D
0  0.960685  0.765729  0.482479  0.496986
1  0.056180  0.186704  0.560583  0.479668
3  0.306238  0.008593  0.496193  0.618088
4  0.782668       NaN  0.156800  0.685145
6  0.440684  0.166032  0.356055  0.007285
7  0.467082  0.115364  0.128460  0.979708
8  0.878624  0.009373  0.023424  0.042076
9       NaN       NaN  0.277863  0.202602

In [96]:
df.dropna(axis=0, how='all', subset=['B', 'A'], inplace=True)

In [97]:
df

          A         B         C         D
0  0.960685  0.765729  0.482479  0.496986
1  0.056180  0.186704  0.560583  0.479668
3  0.306238  0.008593  0.496193  0.618088
4  0.782668       NaN  0.156800  0.685145
5  0.831522  0.642916  0.089744       NaN
6  0.440684  0.166032  0.356055  0.007285
7  0.467082  0.115364  0.128460  0.979708
8  0.878624  0.009373  0.023424  0.042076

## 1.4 异常值处理

体育比赛中，最后算分的时候总会去掉一个最高分，去掉一个最低分，将剩下的分数进行平均。因为从一个非常高的异常值可能会造成对最后结果产生比较大的影响。所以，异常值处理，在统计数据的过程中是必然要介入的一个操作

### 1.4.1 异常值分析

使用describe()函数查看每一列的描述性统计量

order = pd.read_excel("电商用户数据.xlsx")

### 1.4.2 异常值的认定

In [98]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

不符合业务逻辑的异常值

In [ ]:
# cond = df['关注字段'] != '关注的内容'

# cond = df['地址'] != '北京'

# df.loc[cond]

使用均值和标准差进行判断

数据要先满足服从标注正态分布

abs(X) > 3 * X.std()

In [101]:
df = pd.DataFrame(data=np.random.randn(10000, 4), columns=list('ABCD'))

In [102]:
df

             A         B         C         D
0     0.666838 -0.565142  0.500430  0.458141
1    -0.460828  0.307301 -0.143066 -0.622216
2    -0.729785  2.201816 -0.349684  0.826516
3    -0.851272  0.467636  0.643708  0.715152
4    -0.610897  0.142620  0.002293  0.135087
...        ...       ...       ...       ...
9995 -0.440497 -0.003140 -0.378682 -0.215942
9996 -0.817208  0.990282 -0.564558  0.320474
9997 -1.030344 -0.013704  0.254810 -0.063081
9998  0.004801 -0.977229  2.379769  0.746225
9999 -1.331850 -0.095843 -0.794494 -0.519507

[10000 rows x 4 columns]

In [103]:
sns.histplot(df.A)

In [104]:
df.std()

A    0.997676
B    1.005434
C    1.013218
D    1.006631
dtype: float64

In [105]:
df

             A         B         C         D
0     0.666838 -0.565142  0.500430  0.458141
1    -0.460828  0.307301 -0.143066 -0.622216
2    -0.729785  2.201816 -0.349684  0.826516
3    -0.851272  0.467636  0.643708  0.715152
4    -0.610897  0.142620  0.002293  0.135087
...        ...       ...       ...       ...
9995 -0.440497 -0.003140 -0.378682 -0.215942
9996 -0.817208  0.990282 -0.564558  0.320474
9997 -1.030344 -0.013704  0.254810 -0.063081
9998  0.004801 -0.977229  2.379769  0.746225
9999 -1.331850 -0.095843 -0.794494 -0.519507

[10000 rows x 4 columns]

In [108]:
exp_condition = (np.abs(df) > df.std() * 3).any(axis=1)

In [115]:
exp_index = df.loc[exp_condition].index

In [112]:
# 过滤 写出正常值的过滤条件
normal_condition = (np.abs(df) < df.std() * 3).all(axis=1)
df.loc[normal_condition]

             A         B         C         D
0     0.666838 -0.565142  0.500430  0.458141
1    -0.460828  0.307301 -0.143066 -0.622216
2    -0.729785  2.201816 -0.349684  0.826516
3    -0.851272  0.467636  0.643708  0.715152
4    -0.610897  0.142620  0.002293  0.135087
...        ...       ...       ...       ...
9995 -0.440497 -0.003140 -0.378682 -0.215942
9996 -0.817208  0.990282 -0.564558  0.320474
9997 -1.030344 -0.013704  0.254810 -0.063081
9998  0.004801 -0.977229  2.379769  0.746225
9999 -1.331850 -0.095843 -0.794494 -0.519507

[9903 rows x 4 columns]

In [121]:
# 删除指定索引的值
# index <==> labels axis
# df.drop(index=exp_index)
# columns 指定列索引 <==> labels axis=1
df.drop(labels=exp_index, axis=0)

             A         B         C         D
0     0.666838 -0.565142  0.500430  0.458141
1    -0.460828  0.307301 -0.143066 -0.622216
2    -0.729785  2.201816 -0.349684  0.826516
3    -0.851272  0.467636  0.643708  0.715152
4    -0.610897  0.142620  0.002293  0.135087
...        ...       ...       ...       ...
9995 -0.440497 -0.003140 -0.378682 -0.215942
9996 -0.817208  0.990282 -0.564558  0.320474
9997 -1.030344 -0.013704  0.254810 -0.063081
9998  0.004801 -0.977229  2.379769  0.746225
9999 -1.331850 -0.095843 -0.794494 -0.519507

[9903 rows x 4 columns]

使用上四中位数和下四中位数进行异常值判定

In [129]:
order = pd.read_excel('电商用户数据.xlsx')

In [130]:
order.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   统计指标    8 non-null      object
 1   实付金额    8 non-null      float64
 2   邮费      8 non-null      float64
 3   购买数量    8 non-null      float64
dtypes: float64(3), object(1)
memory usage: 388.0+ bytes

In [131]:
order.describe(percentiles=[.99])

               实付金额            邮费          购买数量
count      8.000000      8.000000      8.000000
mean    4206.629783   3606.578959   3617.624302
std    10054.842610  10193.015260  10188.608876
min       30.000000      0.000000      1.000000
50%      120.633285      0.122620      1.497210
99%    27110.440000  26815.950000  26821.690000
max    28833.000000  28833.000000  28833.000000

In [133]:
sns.boxplot(x=order['实付金额'])

In [134]:
# 25 75

Q1, Q3 = np.quantile(order['实付金额'], q=[0.25, 0.75])

IQR = Q3 - Q1

In [139]:
BOTTOM = Q1 - 1.5 * IQR
UPPER = Q3 + 1.5 * IQR

In [141]:
(order['实付金额'] > UPPER).values

array([ True, False, False, False, False, False, False,  True])

In [144]:
condition = (order['实付金额'] > UPPER).values | (order['实付金额'] < BOTTOM).values

In [146]:
exp_index = order.loc[condition].index

In [148]:
order.drop(index=exp_index).describe()

             实付金额        邮费      购买数量
count    6.000000  6.000000  6.000000
mean    99.173044  0.271946  1.332403
std     51.704455  0.554728  0.407887
min     30.000000  0.000000  1.000000
25%     72.442924  0.000000  1.000000
50%     94.385848  0.000000  1.241739
75%    123.449928  0.183930  1.504076
max    178.000000  1.386435  2.000000

## 1.5 重复值处理

In [161]:
df=pd.DataFrame(data=np.random.randint(0,100, size=(10,5)), columns=list('abcde'))
df

    a   b   c   d   e
0   3  67  69  93  42
1  76  64  32  90  18
2  88  97  29  16  43
3  60  43   9  56  17
4  23  13  40  23  34
5  92  37  14  57  41
6  67   6  27  67  16
7  86  52   0  85   5
8  14  73  55   4  16
9   5  86  85  63  23

In [162]:
df.loc[2] = df.loc[6]
df.loc[3] = df.loc[7]
df.loc[8] = df.loc[7]

In [163]:
df.loc[2, 'a'] = 100

In [164]:
df

     a   b   c   d   e
0    3  67  69  93  42
1   76  64  32  90  18
2  100   6  27  67  16
3   86  52   0  85   5
4   23  13  40  23  34
5   92  37  14  57  41
6   67   6  27  67  16
7   86  52   0  85   5
8   86  52   0  85   5
9    5  86  85  63  23

检查

In [167]:
# keep: 保留首次出现的重复值first 还是最后一次出现的重复值last
# subset: 指定，用来判断重复值的列名列表
df.duplicated(keep='first', subset=list('bcde'))

0    False
1    False
2    False
3    False
4    False
5    False
6     True
7     True
8     True
9    False
dtype: bool

过滤

删除

通用的drop函数